# Stage 1: Prepare builder image
FROM --platform=${TARGETPLATFORM} alpine:latest as builder

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

RUN --mount=type=cache,id=apk-cache-${TARGETARCH},target=/var/cache/apk \
	apk add --update --cache-dir=/var/cache/apk \
	binutils \
	bind-tools \
  bison \
	build-base \
	ca-certificates-bundle \
  clang18 \
  coreutils \
  curl \
  gnupg \
  flex \
	libevent-dev \
  nghttp2-dev \
	libsodium-dev \
  linux-headers \
  llvm18 \
	openssl-dev \
  perl \
  protobuf-c \
  protobuf-c-compiler \
  protobuf-c-dev \
  protobuf-dev \
  protoc \
	expat-dev

ARG UNBOUND_UID=101
ARG UNBOUND_GID=102

RUN addgroup -S -g ${UNBOUND_GID} _unbound \
	&& adduser -S -g _unbound -h /var/unbound -u ${UNBOUND_UID} -D -H -G _unbound _unbound

# Stage 2: Build unbound from source
FROM --platform=${TARGETPLATFORM} builder as unbound

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

# Build unbound from source
ENV NAME=unbound \
    UNBOUND_VERSION=1.20.0 \
    UNBOUND_SHA256=08833968bee49d592e3fda9c3bc760de7a21c563d5a8ab5850861af2fd118332 \
    UNBOUND_DOWNLOAD_URL=https://github.com/vincejv/unbound-docker/releases/download/contribs/unbound-master-9603924.tar.gz \
    ROOT_HINTS_URL=https://www.internic.net/domain/named.cache \
    ROOT_HINTS_MD5_URL=https://www.internic.net/domain/named.cache.md5 \
    CFLAGS="-Os -pipe -flto -fomit-frame-pointer" \
    CXXFLAGS="$CFLAGS" \
    CPPFLAGS="$CFLAGS" \
    LDFLAGS="-Os -Wl,--strip-all -Wl,--as-needed" \
    CC=clang-18 \
    CXX=clang++-18

WORKDIR /src

RUN curl -sSL $UNBOUND_DOWNLOAD_URL -o unbound.tar.gz && \
    echo "${UNBOUND_SHA256} *unbound.tar.gz" | sha256sum -c - && \
    tar xzf unbound.tar.gz --strip-components=1 && \
    rm -f unbound.tar.gz && \
    ./configure \
        --prefix=/opt/unbound \
        --with-pthreads \
        --with-username=_unbound \
        --with-libevent \
        --disable-shared \
        --disable-static \
	      --disable-rpath \
        --enable-subnet && \
    make -j$(($(nproc --all)+1)) && \
    make install && \
    rm /opt/unbound/etc/unbound/unbound.conf && \
    rm -rf /opt/unbound/share && \
    curl -sSL $ROOT_HINTS_URL -o root.hints && \
    ROOT_HINTS_MD5_HASHVAL=$(curl -sSL $ROOT_HINTS_MD5_URL) && \
    echo "${ROOT_HINTS_MD5_HASHVAL} *root.hints" | md5sum -c - && \
    mv root.hints /opt/unbound/etc/unbound/root.hints && \
    strip /opt/unbound/sbin/unbound \
          /opt/unbound/sbin/unbound-anchor \
          /opt/unbound/sbin/unbound-checkconf \
          /opt/unbound/sbin/unbound-control \
          /opt/unbound/sbin/unbound-host

# Stage 3: Final image
FROM --platform=${TARGETPLATFORM} busybox:musl
ENV NAME=unbound \
    SUMMARY="${NAME} is a validating, recursive, and caching DNS resolver." \
    DESCRIPTION="${NAME} is a validating, recursive, and caching DNS resolver."

COPY --from=builder /lib/ld-musl*.so.1 /lib/
COPY --from=builder /lib/libcrypto.so.3 /lib/libssl.so.3 /lib/
COPY --from=builder /usr/lib/libsodium.so.* /usr/lib/libevent-2.1.so.* /usr/lib/libexpat.so.* /usr/lib/libprotobuf-c.so.* /usr/lib/
COPY --from=builder /etc/ssl/ /etc/ssl/
COPY --from=builder /etc/passwd /etc/group /etc/

COPY --from=unbound /opt /opt

RUN rm -rf /opt/unbound/include && \
    rm -rf /opt/unbound/lib && \
    rm -rf /opt/openssl

COPY data/ /
RUN chmod +x /unbound.sh

WORKDIR /opt/unbound/

ENV PATH /opt/unbound/sbin:"$PATH"

LABEL org.opencontainers.image.version=${UNBOUND_VERSION} \
      org.opencontainers.image.title="vincejv/unbound" \
      org.opencontainers.image.description="a validating, recursive, and caching DNS resolver" \
      org.opencontainers.image.url="https://github.com/vincejv/unbound-docker" \
      org.opencontainers.image.vendor="Vince Jerald Villamora" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/vincejv/unbound-docker"

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["/unbound.sh"]